import { marked } from "marked";
import { save } from "@tauri-apps/plugin-dialog";
import { writeTextFile } from "@tauri-apps/plugin-fs";
import type { OrchestratedAnalysis, GitHubPR, AgentResponse, AgentFinding, Severity } from "./api";

const AGENT_NAMES: Record<string, string> = {
  security: "Security Agent",
  architecture: "Architecture Agent",
  style: "Style Agent",
  performance: "Performance Agent",
};

const SEVERITY_ORDER: Severity[] = ["critical", "high", "medium", "low", "info"];

const RISK_EMOJI: Record<string, string> = {
  low: "Low",
  medium: "Medium",
  high: "High",
  critical: "Critical",
};

function formatDate(date: Date): string {
  return date.toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}

function groupFindingsBySeverity(findings: AgentFinding[]): Record<Severity, AgentFinding[]> {
  const grouped: Record<Severity, AgentFinding[]> = {
    critical: [],
    high: [],
    medium: [],
    low: [],
    info: [],
  };

  for (const finding of findings) {
    grouped[finding.severity].push(finding);
  }

  return grouped;
}

function formatFinding(finding: AgentFinding): string {
  const location = finding.line
    ? `**${finding.file}:${finding.line}**`
    : `**${finding.file}**`;

  let text = `- ${location} - ${finding.message}`;

  if (finding.suggestion) {
    text += `\n  - *Suggestion:* ${finding.suggestion}`;
  }

  return text;
}

function formatAgentSection(agent: AgentResponse): string {
  const name = AGENT_NAMES[agent.agent_type] || agent.agent_type;
  const lines: string[] = [`## ${name}`];

  if (agent.findings.length === 0) {
    lines.push("");
    lines.push("*No findings*");
    return lines.join("\n");
  }

  const grouped = groupFindingsBySeverity(agent.findings);

  for (const severity of SEVERITY_ORDER) {
    const findings = grouped[severity];
    if (findings.length > 0) {
      lines.push("");
      lines.push(`### ${severity.charAt(0).toUpperCase() + severity.slice(1)} Findings`);
      lines.push("");
      for (const finding of findings) {
        lines.push(formatFinding(finding));
      }
    }
  }

  return lines.join("\n");
}

export function formatAnalysisAsMarkdown(
  analysis: OrchestratedAnalysis,
  pr: GitHubPR,
  owner: string,
  repo: string,
  analysisMode?: string
): string {
  const lines: string[] = [];

  // Header
  lines.push(`# PR Analysis: ${pr.title}`);
  lines.push("");
  lines.push(`**Repository:** ${owner}/${repo}`);
  lines.push(`**PR:** #${pr.number}`);
  lines.push(`**Author:** ${pr.user.login}`);
  lines.push(`**Risk Level:** ${RISK_EMOJI[analysis.risk_level] || analysis.risk_level}`);
  if (analysisMode) {
    lines.push(`**Analysis Mode:** ${analysisMode === "with-context" ? "With Codebase Context" : "PR Only"}`);
  }
  lines.push(`**Generated:** ${formatDate(new Date())}`);
  lines.push("");
  lines.push("---");
  lines.push("");

  // Summary
  lines.push("## Summary");
  lines.push("");
  lines.push(analysis.summary);
  lines.push("");
  lines.push("---");
  lines.push("");

  // Agent Findings
  const agentOrder = ["security", "architecture", "style", "performance"];
  for (const agentType of agentOrder) {
    const agent = analysis.agent_responses.find(a => a.agent_type === agentType);
    if (agent) {
      lines.push(formatAgentSection(agent));
      lines.push("");
      lines.push("---");
      lines.push("");
    }
  }

  // Failed Agents
  if (analysis.failed_agents.length > 0) {
    lines.push("## Failed Agents");
    lines.push("");
    for (const failed of analysis.failed_agents) {
      const name = AGENT_NAMES[failed.agent_type] || failed.agent_type;
      lines.push(`- **${name}**: ${failed.error}`);
    }
    lines.push("");
    lines.push("---");
    lines.push("");
  }

  // Suggested Review Order
  if (analysis.suggested_review_order.length > 0) {
    lines.push("## Suggested Review Order");
    lines.push("");
    for (let i = 0; i < analysis.suggested_review_order.length; i++) {
      lines.push(`${i + 1}. \`${analysis.suggested_review_order[i]}\``);
    }
    lines.push("");
    lines.push("---");
    lines.push("");
  }

  // Footer
  lines.push("*Generated by SiftPR*");

  return lines.join("\n");
}

export async function downloadMarkdown(
  content: string,
  filename: string
): Promise<void> {
  const filePath = await save({
    defaultPath: filename,
    filters: [
      { name: "Markdown", extensions: ["md"] },
      { name: "All Files", extensions: ["*"] },
    ],
  });

  if (filePath) {
    await writeTextFile(filePath, content);
  }
}

const PRINT_STYLES = `
  body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
    line-height: 1.6;
    color: #333;
    max-width: 800px;
    margin: 0 auto;
    padding: 20px;
  }
  h1 {
    color: #1a1a1a;
    border-bottom: 2px solid #eee;
    padding-bottom: 10px;
  }
  h2 {
    color: #2a2a2a;
    margin-top: 30px;
    border-bottom: 1px solid #eee;
    padding-bottom: 8px;
  }
  h3 {
    color: #444;
    margin-top: 20px;
  }
  code {
    background: #f4f4f4;
    padding: 2px 6px;
    border-radius: 3px;
    font-size: 0.9em;
  }
  pre {
    background: #f4f4f4;
    padding: 12px;
    border-radius: 6px;
    overflow-x: auto;
  }
  hr {
    border: none;
    border-top: 1px solid #eee;
    margin: 20px 0;
  }
  ul {
    padding-left: 20px;
  }
  li {
    margin: 8px 0;
  }
  strong {
    color: #1a1a1a;
  }
  em {
    color: #666;
  }
  @media print {
    body {
      padding: 0;
    }
    h1, h2, h3 {
      page-break-after: avoid;
    }
    pre, ul {
      page-break-inside: avoid;
    }
  }
`;

export async function downloadAsHTML(
  markdown: string,
  title: string,
  filename: string
): Promise<void> {
  const html = await marked.parse(markdown);

  const fullHtml = `<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>${title}</title>
    <style>${PRINT_STYLES}</style>
  </head>
  <body>
    ${html}
  </body>
</html>`;

  const filePath = await save({
    defaultPath: filename,
    filters: [
      { name: "HTML", extensions: ["html"] },
      { name: "All Files", extensions: ["*"] },
    ],
  });

  if (filePath) {
    await writeTextFile(filePath, fullHtml);
  }
}
